### ISSUE TITLE
Support for template funcs and variables inside survey questions

### ISSUE THREAD

**Issue by StarpTech** [netzkern/butler#12]
```yml
butlerVersion: ">=0.4.0"
questions:
  - type: input
    name: shorthand
    message: What's the shorthand for this project?
    required: true
  - type: input
    name: maintainer
    message: Who maintains this project?
    default: getShorthand + Vars.email
    required: true
```
